#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['cachelib']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

extras_require = \
{'dynamodb': ['boto3>=1.43.4'],
 'memcached': ['pylibmc>=1.6.3'],
 'mongodb': ['pymongo>=4.11'],
 'redis': ['redis>=6.0.0'],
 'uwsgi': ['uwsgi>=2.0.28'],
 'valkey': ['valkey>=6.1.0']}

setup(name='cachelib',
      version='0.17.0',
      description='A collection of cache libraries in the same API interface.',
      author=None,
      author_email=None,
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      extras_require=extras_require,
      python_requires='>=3.11',
     )
