#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['cachelib']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

setup(name='cachelib',
      version='0.14.0',
      description='A collection of cache libraries in the same API interface.',
      author=None,
      author_email=None,
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      python_requires='>=3.8',
     )
